#ifndef KERNEL_SYSCALL_H
#define KERNEL_SYSCALL_H

#include <nanos/syscall.h>
#include <kernel/types.h>

#define SYSCALL_EXIT ((uint32_t)NANOS_SYSCALL_EXIT)
#define SYSCALL_WAIT_EVENT ((uint32_t)NANOS_SYSCALL_WAIT_EVENT)
#define SYSCALL_POLL_EVENT ((uint32_t)NANOS_SYSCALL_POLL_EVENT)
#define SYSCALL_GET_KEY ((uint32_t)NANOS_SYSCALL_GET_KEY)
#define SYSCALL_GET_BUTTON ((uint32_t)NANOS_SYSCALL_GET_BUTTON)
#define SYSCALL_GET_MOUSE ((uint32_t)NANOS_SYSCALL_GET_MOUSE)
#define SYSCALL_DRAW_WINDOW ((uint32_t)NANOS_SYSCALL_DRAW_WINDOW)
#define SYSCALL_PUT_PIXEL ((uint32_t)NANOS_SYSCALL_PUT_PIXEL)
#define SYSCALL_WRITE_TEXT ((uint32_t)NANOS_SYSCALL_WRITE_TEXT)
#define SYSCALL_PUT_IMAGE ((uint32_t)NANOS_SYSCALL_PUT_IMAGE)
#define SYSCALL_DEFINE_BUTTON ((uint32_t)NANOS_SYSCALL_DEFINE_BUTTON)
#define SYSCALL_PROCESS_INFO ((uint32_t)NANOS_SYSCALL_PROCESS_INFO)
#define SYSCALL_WINDOW_DRAW ((uint32_t)NANOS_SYSCALL_WINDOW_DRAW)
#define SYSCALL_DRAW_RECT ((uint32_t)NANOS_SYSCALL_DRAW_RECT)
#define SYSCALL_GET_SCREEN_SIZE ((uint32_t)NANOS_SYSCALL_GET_SCREEN_SIZE)
#define SYSCALL_APP_CONTROL ((uint32_t)NANOS_SYSCALL_APP_CONTROL)
#define SYSCALL_START_APP ((uint32_t)NANOS_SYSCALL_START_APP)
#define SYSCALL_WAIT_EVENT_TIMEOUT ((uint32_t)NANOS_SYSCALL_WAIT_EVENT_TIMEOUT)
#define SYSCALL_DRAW_LINE ((uint32_t)NANOS_SYSCALL_DRAW_LINE)
#define SYSCALL_SET_EVENT_MASK ((uint32_t)NANOS_SYSCALL_SET_EVENT_MASK)
#define SYSCALL_WRITE_NUMBER ((uint32_t)NANOS_SYSCALL_WRITE_NUMBER)
#define SYSCALL_THREAD ((uint32_t)NANOS_SYSCALL_THREAD)
#define SYSCALL_FILE ((uint32_t)NANOS_SYSCALL_FILE)
#define SYSCALL_IPC ((uint32_t)NANOS_SYSCALL_IPC)

uint32_t syscall_dispatch(uint32_t number, uint32_t arg0, uint32_t arg1,
    uint32_t arg2, uint32_t arg3);

#endif
