#ifndef NANOS_APP_H
#define NANOS_APP_H

#define NANOS_APP_MAGIC 0x3146584e
#define NANOS_APP_HEADER_MAGIC_OFFSET 0
#define NANOS_APP_HEADER_SIZE_OFFSET 4
#define NANOS_APP_HEADER_ENTRY_OFFSET 8
#define NANOS_APP_HEADER_IMAGE_SIZE_OFFSET 12
#define NANOS_APP_HEADER_MEMORY_SIZE_OFFSET 16
#define NANOS_APP_HEADER_STACK_SIZE_OFFSET 20
#define NANOS_APP_HEADER_STACK_TOP_OFFSET 24
#define NANOS_APP_HEADER_ICON_OFFSET_OFFSET 28
#define NANOS_APP_HEADER_SIZE 32

#define NANOS_APP_LOAD_BASE 0x40000000
#define NANOS_APP_STACK_BASE 0x40010000
#define NANOS_APP_STACK_SIZE 4096
#define NANOS_APP_MEMORY_SIZE 8192
#define NANOS_APP_ICON_NONE 0xffffffff
#define NANOS_APP_PARAM_MAX 128

#endif
