#ifndef NANOS_SYSCALL_H
#define NANOS_SYSCALL_H

#define NANOS_SYSCALL_WAIT_EVENT 10
#define NANOS_SYSCALL_POLL_EVENT 11
#define NANOS_SYSCALL_GET_KEY 2
#define NANOS_SYSCALL_GET_BUTTON 17
#define NANOS_SYSCALL_GET_MOUSE 37
#define NANOS_SYSCALL_DRAW_WINDOW 0
#define NANOS_SYSCALL_PUT_PIXEL 1
#define NANOS_SYSCALL_WRITE_TEXT 4
#define NANOS_SYSCALL_PUT_IMAGE 7
#define NANOS_SYSCALL_DEFINE_BUTTON 8
#define NANOS_SYSCALL_PROCESS_INFO 9
#define NANOS_SYSCALL_WINDOW_DRAW 12
#define NANOS_SYSCALL_DRAW_RECT 13
#define NANOS_SYSCALL_GET_SCREEN_SIZE 14
#define NANOS_SYSCALL_APP_CONTROL 18
#define NANOS_SYSCALL_START_APP 19
#define NANOS_SYSCALL_WAIT_EVENT_TIMEOUT 23
#define NANOS_SYSCALL_DRAW_LINE 38
#define NANOS_SYSCALL_SET_EVENT_MASK 40
#define NANOS_SYSCALL_WRITE_NUMBER 47
#define NANOS_SYSCALL_THREAD 51
#define NANOS_SYSCALL_FILE 58
#define NANOS_SYSCALL_IPC 60

#define NANOS_SYSCALL_EXIT 0xffffffff

#define NANOS_WINDOW_DRAW_BEGIN 1
#define NANOS_WINDOW_DRAW_END 2

#define NANOS_NUMBER_FORMAT_DECIMAL 0x000a0000
#define NANOS_NUMBER_FORMAT_HEX 0x00100000

#define NANOS_THREAD_CREATE 1

#define NANOS_APP_CONTROL_KILL 2

#define NANOS_PROCESS_INFO_COUNT 0xffffffff
#define NANOS_PROCESS_INFO_CURRENT 0xfffffffe
#define NANOS_PROCESS_INFO_NAME_MAX 64
#define NANOS_PROCESS_INFO_PID_OFFSET 0
#define NANOS_PROCESS_INFO_APP_PID_OFFSET 4
#define NANOS_PROCESS_INFO_STATE_OFFSET 8
#define NANOS_PROCESS_INFO_SLOT_OFFSET 12
#define NANOS_PROCESS_INFO_PREEMPTS_OFFSET 16
#define NANOS_PROCESS_INFO_IMAGE_SIZE_OFFSET 20
#define NANOS_PROCESS_INFO_STACK_SIZE_OFFSET 24
#define NANOS_PROCESS_INFO_ENTRY_OFFSET_OFFSET 28
#define NANOS_PROCESS_INFO_STACK_TOP_OFFSET 32
#define NANOS_PROCESS_INFO_ICON_OFFSET 36
#define NANOS_PROCESS_INFO_SERVICE_ID_OFFSET 40
#define NANOS_PROCESS_INFO_NAME_OFFSET 44
#define NANOS_PROCESS_INFO_SIZE \
    (NANOS_PROCESS_INFO_NAME_OFFSET + NANOS_PROCESS_INFO_NAME_MAX)
#define NANOS_PROCESS_STATE_EMPTY 0
#define NANOS_PROCESS_STATE_READY 1
#define NANOS_PROCESS_STATE_RUNNING 2
#define NANOS_PROCESS_STATE_EXITED 3

#define NANOS_PATH_MAX 64
#define NANOS_DIRENT_NAME_MAX 64
#define NANOS_DIRENT_NAME_OFFSET 0
#define NANOS_DIRENT_TYPE_OFFSET 64
#define NANOS_DIRENT_SIZE_OFFSET 68
#define NANOS_DIRENT_SIZE 72
#define NANOS_DIRENT_TYPE_FILE 1
#define NANOS_DIRENT_TYPE_DIR 2
#define NANOS_EVENT_NONE 0
#define NANOS_EVENT_REDRAW 1
#define NANOS_EVENT_KEY 2
#define NANOS_EVENT_BUTTON 3
#define NANOS_EVENT_EXIT 4
#define NANOS_EVENT_BACKGROUND 5
#define NANOS_EVENT_MOUSE 6
#define NANOS_EVENT_IPC 7
#define NANOS_EVENT_STACK 8
#define NANOS_EVENT_MASK_REDRAW 0x01
#define NANOS_EVENT_MASK_KEY 0x02
#define NANOS_EVENT_MASK_BUTTON 0x04
#define NANOS_EVENT_MASK_EXIT 0x08
#define NANOS_EVENT_MASK_BACKGROUND 0x10
#define NANOS_EVENT_MASK_MOUSE 0x20
#define NANOS_EVENT_MASK_IPC 0x40
#define NANOS_EVENT_MASK_STACK 0x80
#define NANOS_EVENT_MASK_DEFAULT 0x07
#define NANOS_KEY_CHAR_MASK 0x000000ff
#define NANOS_KEY_SCANCODE_SHIFT 8
#define NANOS_KEY_SCANCODE_MASK 0x0000ff00
#define NANOS_KEY_FLAG_RELEASE 0x00010000
#define NANOS_KEY_FLAG_EXTENDED 0x00020000
#define NANOS_KEY_FLAG_SPECIAL 0x00040000
#define NANOS_KEY_FLAG_SHIFT 0x00080000
#define NANOS_KEY_FLAG_CTRL 0x00100000
#define NANOS_KEY_FLAG_ALT 0x00200000
#define NANOS_KEY_SPECIAL_SHIFT 24
#define NANOS_KEY_SPECIAL_ESCAPE 1
#define NANOS_KEY_SPECIAL_ENTER 2
#define NANOS_KEY_SPECIAL_BACKSPACE 3
#define NANOS_KEY_SPECIAL_TAB 4
#define NANOS_KEY_SPECIAL_LEFT 5
#define NANOS_KEY_SPECIAL_RIGHT 6
#define NANOS_KEY_SPECIAL_UP 7
#define NANOS_KEY_SPECIAL_DOWN 8
#define NANOS_KEY_SPECIAL_HOME 9
#define NANOS_KEY_SPECIAL_END 10
#define NANOS_KEY_SPECIAL_PAGE_UP 11
#define NANOS_KEY_SPECIAL_PAGE_DOWN 12
#define NANOS_KEY_SPECIAL_INSERT 13
#define NANOS_KEY_SPECIAL_DELETE 14
#define NANOS_FILE_READ 0
#define NANOS_FILE_READ_DIR 1
#define NANOS_FILE_REQUEST_OPERATION_OFFSET 0
#define NANOS_FILE_REQUEST_OFFSET_OFFSET 4
#define NANOS_FILE_REQUEST_SIZE_OFFSET 8
#define NANOS_FILE_REQUEST_BUFFER_OFFSET 12
#define NANOS_FILE_REQUEST_PATH_OFFSET 16
#define NANOS_FILE_REQUEST_SIZE 20
#define NANOS_IPC_SEND 1
#define NANOS_IPC_RECV 2
#define NANOS_IPC_BIND_SERVICE 3
#define NANOS_IPC_RESOLVE_SERVICE 4
#define NANOS_IPC_UNBIND_SERVICE 5
#define NANOS_IPC_PENDING 6
#define NANOS_IPC_PEEK 7
#define NANOS_IPC_MESSAGE_SOURCE_OFFSET 0
#define NANOS_IPC_MESSAGE_SIZE_OFFSET 4
#define NANOS_IPC_MESSAGE_DATA_OFFSET 8
#define NANOS_IPC_MESSAGE_DATA_MAX 64
#define NANOS_IPC_MESSAGE_SIZE \
    (NANOS_IPC_MESSAGE_DATA_OFFSET + NANOS_IPC_MESSAGE_DATA_MAX)
#define NANOS_MOUSE_EVENT_X_OFFSET 0
#define NANOS_MOUSE_EVENT_Y_OFFSET 4
#define NANOS_MOUSE_EVENT_SCREEN_X_OFFSET 8
#define NANOS_MOUSE_EVENT_SCREEN_Y_OFFSET 12
#define NANOS_MOUSE_EVENT_BUTTONS_OFFSET 16
#define NANOS_MOUSE_EVENT_TYPE_OFFSET 20
#define NANOS_MOUSE_EVENT_WHEEL_OFFSET 24
#define NANOS_MOUSE_EVENT_SIZE 28
#define NANOS_MOUSE_TYPE_MOVE 1
#define NANOS_MOUSE_TYPE_DOWN 2
#define NANOS_MOUSE_TYPE_UP 3
#define NANOS_MOUSE_TYPE_WHEEL 4
#define NANOS_MOUSE_BUTTON_LEFT 0x01
#define NANOS_MOUSE_BUTTON_RIGHT 0x02
#define NANOS_MOUSE_BUTTON_MIDDLE 0x04
#define NANOS_BUTTON_MAX 16

#ifndef __ASSEMBLER__
struct nanos_dirent {
    char name[NANOS_DIRENT_NAME_MAX];
    unsigned int type;
    unsigned int size;
};

struct nanos_file_request {
    unsigned int operation;
    unsigned int offset;
    unsigned int size;
    void *buffer;
    const char *path;
};

struct nanos_process_info {
    unsigned int pid;
    unsigned int app_pid;
    unsigned int state;
    unsigned int slot;
    unsigned int preempts;
    unsigned int image_size;
    unsigned int stack_size;
    unsigned int entry_offset;
    unsigned int stack_top;
    unsigned int icon_offset;
    unsigned int service_id;
    char name[NANOS_PROCESS_INFO_NAME_MAX];
};

struct nanos_ipc_message {
    unsigned int source_pid;
    unsigned int size;
    unsigned char data[NANOS_IPC_MESSAGE_DATA_MAX];
};

struct nanos_mouse_event {
    int x;
    int y;
    int screen_x;
    int screen_y;
    unsigned int buttons;
    unsigned int type;
    int wheel;
};
#endif

#define NANOS_ERROR_INVALID 0xffffffff

#endif
